// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Table("category")]
public partial class Category
{
    [Key]
    [Column("category_id")]
    public byte CategoryId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(25)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<FilmCategory> FilmCategories { get; set; } = new List<FilmCategory>();
}