// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Table("city")]
[Index("CountryId", Name = "idx_fk_country_id")]
public partial class City
{
    [Key]
    [Column("city_id")]
    public int CityId { get; set; }

    [Required]
    [Column("city")]
    [StringLength(50)]
    [Unicode(false)]
    public string City1 { get; set; }

    [Column("country_id")]
    public short CountryId { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    [ForeignKey("CountryId")]
    [InverseProperty("Cities")]
    public virtual Country Country { get; set; }
}