// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Keyless]
public partial class FilmList
{
    [Column("FID")]
    public int? Fid { get; set; }

    [Column("title")]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Required]
    [Column("category")]
    [StringLength(25)]
    [Unicode(false)]
    public string Category { get; set; }

    [Column("price", TypeName = "decimal(4, 2)")]
    public decimal? Price { get; set; }

    [Column("length")]
    public short? Length { get; set; }

    [Column("rating")]
    [StringLength(10)]
    [Unicode(false)]
    public string Rating { get; set; }

    [Required]
    [Column("actors")]
    [StringLength(91)]
    [Unicode(false)]
    public string Actors { get; set; }
}