// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Table("film")]
[Index("LanguageId", Name = "idx_fk_language_id")]
[Index("OriginalLanguageId", Name = "idx_fk_original_language_id")]
public partial class Film
{
    [Key]
    [Column("film_id")]
    public int FilmId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("release_year")]
    [StringLength(4)]
    [Unicode(false)]
    public string ReleaseYear { get; set; }

    [Column("language_id")]
    public byte LanguageId { get; set; }

    [Column("original_language_id")]
    public byte? OriginalLanguageId { get; set; }

    [Column("rental_duration")]
    public byte RentalDuration { get; set; }

    [Column("rental_rate", TypeName = "decimal(4, 2)")]
    public decimal RentalRate { get; set; }

    [Column("length")]
    public short? Length { get; set; }

    [Column("replacement_cost", TypeName = "decimal(5, 2)")]
    public decimal ReplacementCost { get; set; }

    [Column("rating")]
    [StringLength(10)]
    [Unicode(false)]
    public string Rating { get; set; }

    [Column("special_features")]
    [StringLength(255)]
    [Unicode(false)]
    public string SpecialFeatures { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [InverseProperty("Film")]
    public virtual ICollection<FilmActor> FilmActors { get; set; } = new List<FilmActor>();

    [InverseProperty("Film")]
    public virtual ICollection<FilmCategory> FilmCategories { get; set; } = new List<FilmCategory>();

    [InverseProperty("Film")]
    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    [ForeignKey("LanguageId")]
    [InverseProperty("FilmLanguages")]
    public virtual Language Language { get; set; }

    [ForeignKey("OriginalLanguageId")]
    [InverseProperty("FilmOriginalLanguages")]
    public virtual Language OriginalLanguage { get; set; }
}