// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Table("rental")]
[Index("CustomerId", Name = "idx_fk_customer_id")]
[Index("InventoryId", Name = "idx_fk_inventory_id")]
[Index("StaffId", Name = "idx_fk_staff_id")]
[Index("RentalDate", "InventoryId", "CustomerId", Name = "idx_uq", IsUnique = true)]
public partial class Rental
{
    [Key]
    [Column("rental_id")]
    public int RentalId { get; set; }

    [Column("rental_date", TypeName = "datetime")]
    public DateTime RentalDate { get; set; }

    [Column("inventory_id")]
    public int InventoryId { get; set; }

    [Column("customer_id")]
    public int CustomerId { get; set; }

    [Column("return_date", TypeName = "datetime")]
    public DateTime? ReturnDate { get; set; }

    [Column("staff_id")]
    public byte StaffId { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Rentals")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("InventoryId")]
    [InverseProperty("Rentals")]
    public virtual Inventory Inventory { get; set; }

    [InverseProperty("Rental")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("StaffId")]
    [InverseProperty("Rentals")]
    public virtual Staff Staff { get; set; }
}