// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Keyless]
public partial class SalesByStore
{
    [Column("store_id")]
    public int StoreId { get; set; }

    [Required]
    [Column("store")]
    [StringLength(101)]
    [Unicode(false)]
    public string Store { get; set; }

    [Required]
    [Column("manager")]
    [StringLength(91)]
    [Unicode(false)]
    public string Manager { get; set; }

    [Column("total_sales", TypeName = "decimal(38, 2)")]
    public decimal? TotalSales { get; set; }
}