// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Keyless]
public partial class SalesByFilmCategory
{
    [Required]
    [Column("category")]
    [StringLength(25)]
    [Unicode(false)]
    public string Category { get; set; }

    [Column("total_sales", TypeName = "decimal(38, 2)")]
    public decimal? TotalSales { get; set; }
}