// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDemo.Models;

[Table("staff")]
[Index("AddressId", Name = "idx_fk_address_id")]
[Index("StoreId", Name = "idx_fk_store_id")]
public partial class Staff
{
    [Key]
    [Column("staff_id")]
    public byte StaffId { get; set; }

    [Required]
    [Column("first_name")]
    [StringLength(45)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [Column("last_name")]
    [StringLength(45)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("address_id")]
    public int AddressId { get; set; }

    [Column("picture", TypeName = "image")]
    public byte[] Picture { get; set; }

    [Column("email")]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("store_id")]
    public int StoreId { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Required]
    [Column("username")]
    [StringLength(16)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column("password")]
    [StringLength(40)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("Staff")]
    public virtual Address Address { get; set; }

    [InverseProperty("Staff")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Staff")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    [ForeignKey("StoreId")]
    [InverseProperty("Staff")]
    public virtual Store Store { get; set; }

    [InverseProperty("ManagerStaff")]
    public virtual Store StoreNavigation { get; set; }
}